### ISSUE TITLE
Duplication in full_workflow.py?

### ISSUE THREAD

**Issue by mbjoseph** [wino6687/SWEpy#3]
It looks like there is a bit of duplication of code/copypasta in `full_workflow.py`, where things are converted to string, then spaces are removed, and whitespace is stripped. It looks like there aren't any copy/paste errors, but from a readability perspective it might be worth writing a little function to convert to string and remove spaces instead of making repeated chained function calls. 

https://github.com/wino6687/SWEpy/blob/master/build/lib/swepy/full_workflow.py#L19-L22

**Comment by wino6687** [comment]
Hey @mbjoseph, I need to actually remove full_workflow.py. This was for when the library wasn't pip installable, and provided another way to use the functionality outside of Jupyter. But now that it is installed with the yaml file, I don't think this file is needed anymore? I think It would be better for people to read the documentation and instantiate the class themselves, and then use the Jupyter file for the easy-to-use workflow?

But yes, you are totally right that there is super redundant code in here! I threw it together mostly for testing purposes. There could easily be functions to handle the formatting of dates and such.

**Comment by mbjoseph** [comment]
Ok cool - maybe close this issue after deleting the file?
