### ISSUE TITLE
NSIDC licensing clarification

### ISSUE THREAD

**Issue by mbjoseph** [wino6687/SWEpy#4]
It seems like this library includes code from other libraries: https://github.com/wino6687/SWEpy/tree/master/build/lib/swepy

Are there any licensing concerns with this @carsonfarmer? Does it make sense to amend the `LICENSE` file to clarify which parts of the code are under the MIT license, and which parts are copyrighted by CU Boulder? Also are there any issues with us distributing their code like this, given the copyright that seems to be attached to it (e.g., https://github.com/wino6687/SWEpy/blob/master/build/lib/swepy/ease2conv.py#L21)?

**Comment by wino6687** [comment]
Hey @mbjoseph , I was very unclear in this area and would love guidance! Ease2conv is only here because I needed it to be in python 3, and I wasn't sure of any other way to use it since their library is in python 2.7. I made sure all of their info was in the code clearly, but maybe there's another way to use this script without having it locally?

**Comment by carsonfarmer** [comment]
Hmm, I see the copyright there, but not what license it was released under. @wino6687 any license file associated with that code? If its an open source license, I think we'll be ok. We'll just have to update the license file as suggested by @mbjoseph. MIT might be too permissive depending on the ease2conv code?

**Comment by wino6687** [comment]
Hey @carsonfarmer  and @mbjoseph, [Here is the link](https://bitbucket.org/nsidc/cetbtools/src) to the cetbtools source repo on bitbucket. I don't see a License in here like there usually is. It is under the NSDIC/PMESDR umbrella in bitbucket, so I am pretty sure it is open source? 

Maybe I am just looking in the wrong spot for the license?

**Comment by mbjoseph** [comment]
@wino6687 let me know if you want help drafting an e-mail to ask about licensing stuff!

**Comment by wino6687** [comment]
@mbjoseph  that would be great! I am out of town at the moment. But I can draft an email when I get back and i'll send it to you for additions/edits. I don't know much about licensing, so some help with the standards and expectations is very much needed.

**Comment by wino6687** [comment]
@mbjoseph and @carsonfarmer, I spoke with the NSDIC and cetbtools should now be available in python 3. It is accessible through the NSIDC conda channel, though, and so when I include it as a dependency in the meta.yaml file for my conda release, it throws an error. After doing some digging, I don't see a way to include multiple channels in a conda build recipe... 

For right now I am going to get a yaml file working and then delete the local copy of EASE2Transform, but I would like to figure out how to get everything working with a simple conda install.

**Comment by wino6687** [comment]
@mbjoseph and @carsonfarmer, SWEpy now includes cetbtools in the yml file for constructing the necessary environment, so I have gone ahead and deleted all of the local NSIDC code from this repo. I'm working on moving to a conda build of swepy to ditch the yaml altogether. 

I'm going to go ahead and close this issue!

**Comment by carsonfarmer** [comment]
If your code depends on the cetbtools code, then even if you don't have a local version of the code, you still need to make sure the licenses are compatible. Under what license have their released the code in their conda repo?

**Comment by wino6687** [comment]
@carsonfarmer, she said she had forgotten to put a license in the repo, and I don't think it is up yet. But on the anaconda package it says "GPlv3", which is a link that leads to opensource.org. Here is the [gplv3](https://www.gnu.org/licenses/gpl-3.0.en.html) info page.

**Comment by carsonfarmer** [comment]
Hmm. Ok, then your code will also have to be gpl v3 or later. Maybe ask if they’ll use a more permissive license like bsd or mit? It just makes packaging for python easier, and means it’s more useful to private sector folks.

**Comment by wino6687** [comment]
I have a meeting with Mary Jo on the 17th to discuss this and the conda channels we are using. It was the first available time. I can ask her if she can use a more permissive license for sure.

**Comment by wino6687** [comment]
There is no longer a dependency on cetbtools in SWEpy, so I will go ahead and close this issue. I am now using cartopy for coordinate conversions
