### ISSUE TITLE
Consider a more general introduction to the project

### ISSUE THREAD

**Issue by usethedata** [wino6687/SWEpy#6]
The lead sentence in the documentation is

> SWEpy is a python library designed to give you quick and easy access to temperature brightness imagery stored in the MEaSUREs dataset in the NSIDC 0630 database.

While there's some truth to the idea that people who don't understand what that sentence means are unlikely to be able to get much value from this particular project, I think a more accessible introduction does make sense.  Perhaps something along the lines of

> SWEpy is a Python library designed to simplify access to a northern hemisphere passive microwave brightness temperature dataset available at the National Snow and Ice Data Center (NSIDC).

**Comment by wino6687** [comment]
Hi @usethedata, sorry I missed this issue somehow! That is a good suggestion, and I will work on that right away.
